blogTitle = "archie hicklin"
subTitle = "blog"
blogUrl = "blog.archiehickl.in"
authorName = "Archie Hicklin"
authorBio = "contact — <a href='mailto:motoco@protonmail.com'>secure email</a>"
linkPrefix = "/gatsby-starter-drunkenblog"
# gaCode = "UA-0000000-0"
# disqusShortname = "yoursite"
# kommentsCode = "00000000-0000-0000-0000-000000000000"
